name: Checkout and Build .NET project
description: Checkout and build a .NET project
inputs:
  project_folder:
    description: 'Project folder to build'
    required: true
  project_structure:
    description: 'Project structure to checkout only the necessary files'
    required: true
  checkout_to_path:
    description: 'Path to checkout the project'
    required: false
  github_workspace:
    description: 'Github workspace path'
    required: true

runs:
  using: 'composite' 
  steps:
    - name: Set environment variables
      run: echo "PROJECT_PATH=${{inputs.checkout_to_path != '' && format('{0}/{1}', inputs.checkout_to_path, inputs.project_folder) || inputs.project_folder}}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
      with:
        sparse-checkout: ${{ inputs.project_structure }}
        path: ${{ inputs.checkout_to_path }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: '**/packages.lock.json'
    - name: Restore dependencies
      env:
        NUGET_PACKAGES: ${{ env.GITHUB_WORKSPACE }}/.nuget/packages
      run: dotnet restore ${{ env.PROJECT_PATH }} --locked-mode
    - name: Build
      run: dotnet publish ${{ env.PROJECT_PATH }} --runtime win-x64 --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-build --verbosity normal
