name: Checkout and Build .NET project
description: Checkout and build a .NET project
inputs:
  project_folder:
    description: 'Project folder to build'
    required: true
  project_structure:
    description: 'Project structure to checkout only the necessary files'
    required: true
  checkout_to_path:
    description: 'Path to checkout the project'
    required: false
  github_workspace:
    description: 'Github workspace path'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: ${{ inputs.project_structure }}
        path: ${{ inputs.checkout_to_path }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: '**/packages.lock.json'
    - name: Restore dependencies
      working-directory: ${{ inputs.checkout_to_path }}
      shell: bash
      env:
        NUGET_PACKAGES: $GITHUB_WORKSPACE/.nuget/packages
      run: dotnet restore ${{ inputs.project_folder }} --locked-mode
    - name: Build
      working-directory: ${{ inputs.checkout_to_path }}
      shell: bash
      env:
        NUGET_PACKAGES: $GITHUB_WORKSPACE/.nuget/packages
      run: dotnet publish ${{ inputs.project_folder }} --runtime win-x64 --configuration Release --no-restore
    - name: Test
      working-directory: ${{ inputs.checkout_to_path }}
      shell: bash
      env:
        NUGET_PACKAGES: $GITHUB_WORKSPACE/.nuget/packages
      run: dotnet test ${{ inputs.project_folder }} --no-build --verbosity normal
