name: Checkout and Build .NET project
description: Checkout and build a .NET project, with caching dependencies.

inputs:
  project_folder:
    description: 'Project folder to build'
    required: true
  project_structure:
    description: 'Project structure to checkout only the necessary projects.'
    required: true
  publish_to_path:
    description: 'Path to publish the project to'
    required: false
  version:
    required: false
    default: 8.0.x

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: ${{ inputs.project_structure }}
        path: ${{ inputs.publish_to_path }}
    - name: Set Environment Variables
      shell: bash
      run: echo "NUGET_PACKAGES=$GITHUB_WORKSPACE/.nuget/packages" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.version }}
        cache: true
        cache-dependency-path: '**/packages.lock.json'
    - name: Restore dependencies
      working-directory: ${{ inputs.publish_to_path }}
      shell: bash
      run: dotnet restore ${{ inputs.project_folder }} --locked-mode
    - name: Build
      working-directory: ${{ inputs.publish_to_path }}
      shell: bash
      run: dotnet publish ${{ inputs.project_folder }} --runtime win-x64 --configuration Release --no-restore
    - name: Test
      working-directory: ${{ inputs.publish_to_path }}
      shell: bash
      run: dotnet test ${{ inputs.project_folder }} --no-build --verbosity normal
