name: .Net Build and push to history branch (Not the same)
on:
  workflow_call:
    secrets:
      PUBLISH_TOKEN:
        description: 'A token passed from the caller workflow'
        required: true
    inputs:
      target_repository:
        description: 'Repository to deploy to (e.g. owner/repo)'
        required: true
        type: string
      target_branch:
        description: 'Branch to deploy to'
        required: true
        type: string
      project_folder:
        description: 'Project folder to build'
        required: true
        type: string
      project_structure:
        description: 'Project structure to checkout'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: false
        type: string
      push:
        description: 'Push changes to target repository'
        required: false
        type: boolean
        default: true

env:
  PROJECT_PATH: main/${{ inputs.project_folder }}
  TARGET_PATH: target
  
  OWN_ACTION_REPOSITORY: Erdu-EC/Github-Actions
  OWN_ACTION_BRANCH: main

jobs:
  build:
    name: Build .NET project
    runs-on: ubuntu-latest
    environment: ${{ inputs.push && inputs.environment || '' }}
    steps:
      - name: Prepare local github actions
        uses: actions/checkout@v4
        with:
          repository: ${{ env.OWN_ACTION_REPOSITORY }}
          ref: ${{ env.OWN_ACTION_BRANCH }}
          sparse-checkout: |
            .github/actions/net-core-build/action.yml
            .github/actions/commit-message/action.yml
          sparse-checkout-cone-mode: false
      - name: Checkout and build with cache
        uses: ./.github/actions/net-core-build
        with:
          project_folder: ${{ inputs.project_folder }}
          project_structure: ${{ inputs.project_structure }}
          checkout_to_path: main
      - name: Checkout deploy repository
        if : inputs.push
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.target_repository}}
          token: ${{ secrets.PUBLISH_TOKEN }}
          ref: ${{ inputs.target_branch }}
          path: target
      - name: Move binaries to deploy repository
        if : inputs.push
        run: |
          #Preserve git history.
          mkdir -p ${{ inputs.project_folder }}
          cp -r ${{ env.TARGET_PATH }}/.git ${{ inputs.project_folder }}
          
          #Remove old files and copy new files. 
          rm -r -f ${{ env.TARGET_PATH }}
          mkdir -p ${{ env.TARGET_PATH }}
          mv ${{ env.PROJECT_PATH }}/bin/Release/net8.0/win-x64/publish/* ${{ env.TARGET_PATH }}
          
          #Restore git history.
          mv ${{ inputs.project_folder }}/.git ${{ env.TARGET_PATH }}
          
          #Prepare push changes
          cd ${{env.TARGET_PATH}}
          git config user.name "HS Publisher [bot]"
          git config user.email "hunterstars+github-actions[bot]@hunterstars.noreply.github.com"
          git add --sparse .
      - name: Push changes
        if : inputs.push
        uses: ./.github/actions/commit-message
        with:
          cd: ${{ env.TARGET_PATH }}
          push: ${{ inputs.push }}