name: Node.js Build and Push to history branch (Not needed be in the same repository)
on:
  workflow_call:
    inputs:
      app_folder:
        description: 'App folder to build'
        required: true
        type: string
      app_structure:
        description: 'App structure to checkout, optional, default is app_folder'
        required: false
        type: string

jobs:
  build:
    name: Build App with Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Get app files from repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.app_structure || inputs.app_folder }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        working-directory: ${{ inputs.app_folder }}
        run: npm ci

      - name: Build App
        working-directory: ${{ inputs.app_folder }}
        run: npm run build
